### PR TITLE
Fix AllToSolr exporter misnamed variables

### PR DESCRIPTION
**Pull request by jthomale**
Extremely simple change. Two variables in export.batch_exporters.AllToSolr methods were misnamed
(export_name), causing Django to throw an error when running the export.
Fixes issue #15.

### CODE REVIEW

**Comment by jthomale** [comment]
@vphill @damonkelley @somexpert @jason-ellis @ldko Feel free to take a look; I know it's a stupid small change, but am trying to get some semblance of a workflow so I don't have to think about it each time.

**Comment by somexpert** [comment]
It looks like both renames are for an identical variable in both situations. Can we use either `p_name` _or_ `process_name` for both?

**Comment by jthomale** [comment]
Ha--yeah looking at both of those blocks, I have totally inconsistent variable names between the two, where they are variables for identical things. I must have been trying to fit stuff in the 80 lines and just abbreviated different ways. I'll clean that up. Good catch.

**Comment by jthomale** [comment]
@somexpert Fixed variable names in those two blocks that were inconsistent, 9e45a25.

**Comment by somexpert** [comment]
:thumbsup:

**Comment by damonkelley** [comment]
:tada: :+1:

**Comment by jthomale** [comment]
I rebased issue-15 locally onto master before merging, but neglected to push the issue-15 branch back to GH after the rebase--I just rebased locally, then merged with master, and then pushed master up. So the PR didn't get linked to the merge. Next time I will force push the branch to GH after the rebase so that the PR gets resolved automatically.

**Pull request closed without merging**
